### ISSUE TITLE
来一份 B360+i7 8700 +RX 560的配置哇

### ISSUE THREAD

**Issue by 44886** [huangyz0918/Hackintosh-Installer-University#16]
华硕B360M-basalt主板
i7 8700CPU
蓝宝石 rx560 显卡

**Comment by huangyz0918** [comment]
You can have a try with that: [EFI.zip](https://www.tonymacx86.com/attachments/efi-zip.333440/)

**Comment by 44886** [comment]
@huangyz0918 这主板就是有集显呢，好像是 UHD 630

**Comment by 44886** [comment]
@huangyz0918 我先试试你的这个EFI.zip，谢谢
