### ISSUE TITLE
New sections

### ISSUE THREAD

**Issue by hieplpvip** [huangyz0918/Hackintosh-Installer-University#22]
We already have Post-Installation section. Should we create two new sections for Pre-Installation and Installation?

Also, what should I write in System Installation section?

**Comment by huangyz0918** [comment]
@hieplpvip Installation section is not so necessary, we can write more about pre-installation and post-installation. That's the key point. I think @Xc2333 may be interested in the pre-installation part. Including the:

- how to create a USB bootable device?
- how to install the bootloader program inside the local drive?
- how to custom the bootloader or fix the kp?

 ,etc. I will help to improve the writings and I like playing with hardwares, so I really want to start something with DSDT or flashing the BIOS whitelist or so. :)

**Comment by Xc2333** [comment]
Agree！

@huangyz0918 I will take over something about bootloader.
