### ISSUE TITLE
clone 下载不全

### ISSUE THREAD

**Issue by cn-umbrella** [huangyz0918/Hackintosh-Installer-University#28]
https://github.com/huangyz0918/Hackintosh-Installer-University/tree/master/Clover-Configs/Lenovo/Y470/CLOVER

**Comment by huangyz0918** [comment]
这里已经提供了：

- ACPI 补丁，DSDT, SSDT
- Config 配置
- 必要的 Drivers 
- 必要的 kexts 

请问你还需要什么？？

**Comment by williambj1** [comment]
可能是由于储存库东西太多了，我clone会报错然后丢东西
