### ISSUE TITLE
Add Acer Aspire A515

### ISSUE THREAD

**Issue by SiddheshNan** [huangyz0918/Hackintosh-Installer-University#46]
Hello, can you please add Acer A515-51G repo into the list?
https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh
Thanks in advance.

**Comment by huangyz0918** [comment]
Yes, you can open a pull request if possible. Thanks for your contribution.

**Comment by SiddheshNan** [comment]
Sure, Thanks!
